spring:
  datasource:
    dynamic:
      enabled: true
      strict: true
      primary: "mysql-base"


---
spring:
  config:
    activate:
      on-profile: dev




---
spring:
  config:
    activate:
      on-profile: prod








