spring:
  datasource:
    dynamic:
      enabled: true
      strict: true
      primary: "mysql-base"


---
spring:
  config:
    activate:
      on-profile: zard

  datasource:
    hikari:
      mysql-base:
        jdbc-url: jdbc:mysql://43.240.220.45:3306/zard_oss?allowLoadLocalInfile=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&rewriteBatchedStatements=true
        username: zard_oss
        password: zard_oss
        maximum-pool-size: 100
        idle-timeout: 60000
        connection-timeout: 30000

---
spring:
  config:
    activate:
      on-profile: prod








