
spring:
  flyway:
    enabled: false

---
spring:
  config:
    activate:
      on-profile: zard

biz:
  base:
    flyway-mysql-base:
      enabled: false
      locations:
        - "sqls/mysql"
    flyway-pgsql-base:
      enabled: false
      locations:
        - "sqls/pgsql"


---
spring:
  config:
    activate:
      on-profile: dev


