
spring:
  redis:
    timeout: PT1S
    connect-timeout: PT5S
    lettuce:
      pool:
        enabled: true
        max-active: 1000
        max-wait: PT2S
        max-idle: 500
        min-idle: 10


---
spring:
  config:
    activate:
      on-profile: zard

  redis:
    open: false
    database: 3
    host: 192.168.8.124
    port: 6379
    password: zard
    timeout: 6000ms
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 10
        min-idle: 5
# 目前暂时没用到redis

---
spring:
  config:
    activate:
      on-profile: dev


